# ************************************************************************
# Product    : Home information and control
# Date       : 2016-12-13
# Copyright  : Copyright (C) 2016 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : base-nodejs-owfs/Dockerfile-rpi
# Version    : 0.1.0
# Author     : Bjorn Kjeholt
# *************************************************************************
 
FROM hypriot/rpi-node:latest

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

RUN apt-get update && \
    apt-get install -y vim \
                       ow-shell \
                       owserver && \
    rm -rf /var/lib/apt/lists*

RUN mkdir -p /usr/src/app && \
    mkdir -p /usr/src/app/js && \
    mkdir -p /usr/src/app/script && \
    mkdir -p /mnt/1wire
    
WORKDIR /usr/src/app

# Install app dependencies

ONBUILD COPY package.json package.json
ONBUILD RUN npm install

# Bundle app source
ONBUILD COPY js /usr/src/app/js
# ONBUILD COPY Scripts /usr/src/app/script

ONBUILD RUN chmod -f 755 /usr/src/app/script/* && \
            chmod -f 755 /usr/src/app/*

COPY Configs/owfs.conf /etc/owfs.conf

VOLUME /mnt/1wire
EXPOSE 4304

ONBUILD ENTRYPOINT /usr/bin/owserver -c /etc/owfs.conf --foreground

ONBUILD CMD ["npm","start"]

