#!/bin/sh
DOCKER_HUB_NAME=${1}
DOCKER_IMAGE_NAME=${2}
DOCKER_IMAGE_BASE_TAG=${3}
BUILD_NUMBER=${4}
ARCHITECTURE=${5}

DOCKER_IMAGE_FULL_NAME=${DOCKER_HUB_NAME}/${DOCKER_IMAGE_NAME}
DOCKER_IMAGE_TAG=${DOCKER_IMAGE_BASE_TAG}-${BUILD_NUMBER}-${ARCHITECTURE}

DOCKERFILE_PATH=Dockerfile-${ARCHITECTURE}

# Start the build

docker build -f ${DOCKERFILE_PATH} \
             --build-arg BUILD_REV=${DOCKER_IMAGE_BASE_TAG}-${BUILD_NUMBER} \
             -t ${DOCKER_IMAGE_FULL_NAME}:${DOCKER_IMAGE_TAG} .

docker push ${DOCKER_IMAGE_FULL_NAME}:${DOCKER_IMAGE_TAG}
